name: Ubuntu - Memcpy Naive implementation Tests

on: push

permissions:
  contents: write

jobs:
  build: 
    runs-on: [ubuntu-latest]
    steps: 
      - name: Checkout repository ${{ github.repository }} on a branch ${{ github.ref_name }} triggered by ${{ github.event_name }}
        uses: actions/checkout@v4
      
      - run: "echo the ${{ github.repository }} has been cloned in the container !"

      - name: ğŸ”„ Installing task...
        uses: arduino/setup-task@v1
        with:
          version: 3.x

      - uses: actions/setup-python@v5
        with:
          cache: 'pip'
      
      - name: ğŸ”„ Installing Meson package build system...
        run: pip install meson

      - name: ğŸ”„ Installing Dependencies...
        run: |
          sudo apt-get update
          echo "ğŸ“¦ Installing libcriterion-dev, Ninja, GCC New Version"
          sudo apt-get install -y libcriterion-dev ninja-build gcc-12
          sudo ln -s -f /usr/bin/gcc-12 /usr/bin/gcc
          echo "âœ… Dependencies installed!"

      - name: Build tests and run Memcpy Naive tests
        run: |
          echo "ğŸ—ï¸ Setting up Meson build system..."
          task build-tests
          echo "ğŸ‰ Build completed with Meson!"
          task run-test-suite -- $(task list-tests | grep "test_memcpy_naive")
